security:
    # Password hasher configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider (in-memory)
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$/LvdvPMyToYmwgCOd//lyOYKYVpa9e3ECCTIFIZYhUsrayUvzNLki'
                        roles: [ 'ROLE_ADMIN' ]
                    user:
                        password: '$2y$13$/LvdvPMyToYmwgCOd//lyOYKYVpa9e3ECCTIFIZYhUsrayUvzNLki'
                        roles: [ 'ROLE_USER' ]

    # Firewall configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: in_memory
            http_basic: ~
            lazy: true

    # Access control rules
    access_control:
      - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
